version: 2

sources:
  - name: raw_csv
    schema: raw_csv
    tables:
      - name: customers
      - name: delivery_events
      - name: driver_monthly_metrics
      - name: drivers
      - name: facilities
      - name: fuel_purchases
      - name: loads
      - name: maintenance_records
      - name: routes
      - name: safety_incidents
      - name: trailers
      - name: trips
      - name: truck_utilization_metrics
      - name: trucks
